name: IMM Opportunity Scanner

on:
  schedule:
    - cron: '0 6 * * 1'   # Mondays 06:00 UTC (~09:00 Israel summer)
  workflow_dispatch: {}

jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pytest
        run: pytest -q

  scan:
    name: Weekly IMM scan
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run agent
        env:
          BASE_CURRENCY: ILS
          MIN_BUDGET_ILS: 20000
          FX_API_BASE_URL: https://api.exchangerate.host
          FX_API_KEY: ${{ secrets.FX_API_KEY }}
        run: |
          PYTHONPATH=src python src/agent.py
      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: imm-opportunities
          path: opportunities_*.csv
